### PR TITLE
Fix undefined symbol `x' error

### PR DESCRIPTION
**Pull request by poulsbo**
Attempt to fix runtime ruby exception when running with BlahTeX.

### CODE REVIEW

**Comment by distler** [comment]
Thanks. Dunno how the "x" got there.

**Comment by poulsbo** [comment]
Actually never mind. With this fix, I just hit a different error:

```
Processing WikiController#save (for 10.0.2.2 at 2016-01-25 04:43:44) [POST]
  Parameters: {"_form_key"=>"6766d8dec0add82e50450a44fce0d965f4adce98", "content"=>"# Test\r\n\r\nCan I get a $\\alpha$?", "new_name"=>"HomePage", "author"=>"AnonymousCoward", "web"=>"wiki", "id"=>"HomePage"}
Reading page 'HomePage' from web 'wiki'
Page 'HomePage'  found
10.0.2.2
10.0.2.2
Reading page 'HomePage' from web 'wiki'
Page 'HomePage'  found

NoMethodError (undefined method `src' for #<IO:<STDERR>>):
  vendor/bundle/ruby/2.3.0/bundler/gems/maruku-b5e90a2e37d2/lib/maruku/ext/math/to_html.rb:82:in `adjust_png'
  vendor/bundle/ruby/2.3.0/bundler/gems/maruku-b5e90a2e37d2/lib/maruku/ext/math/to_html.rb:113:in `to_html_inline_math'
  vendor/bundle/ruby/2.3.0/bundler/gems/maruku-b5e90a2e37d2/lib/maruku/output/to_html.rb:871:in `block in array_to_html'
  vendor/bundle/ruby/2.3.0/bundler/gems/maruku-b5e90a2e37d2/lib/maruku/output/to_html.rb:864:in `each'
  vendor/bundle/ruby/2.3.0/bundler/gems/maruku-b5e90a2e37d2/lib/maruku/output/to_html.rb:864:in `array_to_html'
  vendor/bundle/ruby/2.3.0/bundler/gems/maruku-b5e90a2e37d2/lib/maruku/output/to_html.rb:859:in `children_to_html'
  vendor/bundle/ruby/2.3.0/bundler/gems/maruku-b5e90a2e37d2/lib/maruku/output/to_html.rb:312:in `wrap_as_element'
  vendor/bundle/ruby/2.3.0/bundler/gems/maruku-b5e90a2e37d2/lib/maruku/output/to_html.rb:393:in `to_html_paragraph'
  vendor/bundle/ruby/2.3.0/bundler/gems/maruku-b5e90a2e37d2/lib/maruku/output/to_html.rb:871:in `block in array_to_html'
  vendor/bundle/ruby/2.3.0/bundler/gems/maruku-b5e90a2e37d2/lib/maruku/output/to_html.rb:864:in `each'
  vendor/bundle/ruby/2.3.0/bundler/gems/maruku-b5e90a2e37d2/lib/maruku/output/to_html.rb:864:in `array_to_html'
  vendor/bundle/ruby/2.3.0/bundler/gems/maruku-b5e90a2e37d2/lib/maruku/output/to_html.rb:859:in `children_to_html'
  vendor/bundle/ruby/2.3.0/bundler/gems/maruku-b5e90a2e37d2/lib/maruku/output/to_html.rb:23:in `to_html'
  lib/chunks/engines.rb:110:in `mask'
  lib/chunks/engines.rb:20:in `apply_to'
  lib/wiki_content.rb:182:in `build_chunks'
  lib/wiki_content.rb:158:in `initialize'
  lib/page_renderer.rb:140:in `new'
  lib/page_renderer.rb:140:in `render'
  lib/page_renderer.rb:29:in `display_content'
  app/models/page.rb:26:in `revise'
  app/models/wiki.rb:79:in `revise_page'
  app/controllers/wiki_controller.rb:347:in `save'
  vendor/bundle/ruby/2.3.0/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
  vendor/bundle/ruby/2.3.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
  vendor/bundle/ruby/2.3.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
  vendor/bundle/ruby/2.3.0/gems/thin-1.6.4/lib/thin/connection.rb:53:in `process'
  vendor/bundle/ruby/2.3.0/gems/thin-1.6.4/lib/thin/connection.rb:39:in `receive_data'
  vendor/bundle/ruby/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
  vendor/bundle/ruby/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
  vendor/bundle/ruby/2.3.0/gems/thin-1.6.4/lib/thin/backends/base.rb:73:in `start'
  vendor/bundle/ruby/2.3.0/gems/thin-1.6.4/lib/thin/server.rb:162:in `start'
  instiki:6:in `load'
  instiki:6:in `<main>'
```

I'm going to try the latest Maruku.

**Comment by distler** [comment]
What's `10.0.2.2` ?

And just FYI: Ruby 2.3.x requires the latest Instiki trunk for full compatibility.

**Comment by poulsbo** [comment]
I'm on the tip of master at distler/maruku.

**Comment by distler** [comment]
>I'm on the tip of master at distler/maruku.

I was referring to `parasew/instiki`.

**Comment by poulsbo** [comment]
Sorry, my mistake -- that's what I meant as well!



On Sun, Jan 24, 2016 at 9:49 PM -0800, "Jacques Distler" <notifications@github.com> wrote:













I'm on the tip of master at distler/maruku.




I was referring to parasew/instiki.

**Comment by distler** [comment]
Good!

I assume you've followed [these instructions](https://golem.ph.utexas.edu/wiki/instiki/show/BlahTeX) and tested the `blahtex` commandline utility directly (as I said, in the installation notes, if your commandline TeX setup is not working in some way, `blahtex` won't either).

**Comment by poulsbo** [comment]
Yes, precisely. I'm on Linux, and using TeX Live with a medium install. Blahtex invoked directly can generate both MathML and PNG.
I'll try ruby 2.2.4 tomorrow.



On Sun, Jan 24, 2016 at 10:16 PM -0800, "Jacques Distler" <notifications@github.com> wrote:












Good!



I assume you've followed these instructions and tested the blahtex commandline utility directly (as I said, in the installation notes, if your commandline TeX setup is not working in some way, blahtex won't either).

**Pull request merged**
